### ISSUE TITLE
Using system templates seems to be broken

### ISSUE THREAD

**Issue by jacobtomlinson** [jacobtomlinson/krontab#29]
```
$ krontab run job --template pangeo --command 'echo hello'
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jacobtomlinson/krontab/crontab.KronJob.Construct(0x7fffb3d173c9, 0x6, 0x11d2862, 0x8, 0x11d2c0b, 0x9, 0x7fffb3d173da, 0xa, 0x1256200, 0x9, ...)
        /home/travis/gopath/src/github.com/jacobtomlinson/krontab/crontab/crontab.go:96 +0x5ba
github.com/jacobtomlinson/krontab/crontab.KronJob.Run(0x7fffb3d173c9, 0x6, 0x11d2862, 0x8, 0x11d2c0b, 0x9, 0x7fffb3d173da, 0xa, 0x3, 0x3, ...)
        /home/travis/gopath/src/github.com/jacobtomlinson/krontab/crontab/crontab.go:115 +0x67
github.com/jacobtomlinson/krontab/crontab.RunJob(0xc00027cb80, 0x1, 0x4, 0x7fffb3d173c9, 0x6, 0xc000159cb0, 0xc000159c80, 0x0, 0x0)
        /home/travis/gopath/src/github.com/jacobtomlinson/krontab/crontab/crontab.go:417 +0x13a
github.com/jacobtomlinson/krontab/cmd.glob..func11(0x1c423a0, 0xc00027cb80, 0x1, 0x4)
        /home/travis/gopath/src/github.com/jacobtomlinson/krontab/cmd/run.go:27 +0xb0
github.com/spf13/cobra.(*Command).execute(0x1c423a0, 0xc00027cb40, 0x4, 0x4, 0x1c423a0, 0xc00027cb40)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x1c41ee0, 0x0, 0x1c42600, 0xc000159f58)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x1c41ee0, 0x4056b0, 0xc0000ac058)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
github.com/jacobtomlinson/krontab/cmd.Execute()
        /home/travis/gopath/src/github.com/jacobtomlinson/krontab/cmd/root.go:44 +0x2d
main.main()
        /home/travis/gopath/src/github.com/jacobtomlinson/krontab/main.go:8 +0x20
```

**Comment by jacobtomlinson** [comment]
This appears to be due to a malformed template.
